import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Login from './login';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yat | Yet Another Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css' />
      </Head>
      <Login />
    </div>
  )
}
